### ISSUE TITLE
Implement new collector class that will give pod-container logs 

### ISSUE THREAD

**Issue by sophsoph321** [Azure/aks-periscope#105]
The container logs collector class got removed from the periscope repo in this PR: https://github.com/Azure/aks-periscope/pull/97 
For arc requirements, we need container logs for the azure-arc namespace as long as the collector is configurable to any namespace, we should be fine. 
Implementation details of this new collector class can be worked out in this thread or offline.

**Comment by Tatsinnit** [comment]
Cool, Thanks for Clarification @sophsoph321, so this means we need `Pod-Container logs` which makes sense:

As a help, I could land up a feature branch for you with fetch of pods-container-logs and other pod level information, you can improve on it. (If this helps)

* Here is a sample implementation and we can do that using `client-go` https://github.com/kubernetes/kubernetes/blob/c2e90cd1549dff87db7941544ce15f4c8ad0ba4c/pkg/kubectl/cmd/log.go#L141 

![image](https://user-images.githubusercontent.com/6233295/131414654-19f8a7b0-293a-4630-aa98-e43c76ff321a.png)

**Comment by sophsoph321** [comment]
> Cool, Thanks for Clarification @sophsoph321, so this means we need `Pod-Container logs` which makes sense:
> 
> **As a help for you**, I could land up a feature branch for you with `client-go` implementation of fetch of pods-container-logs and other pod level information, you can improve on it. (If this helps)
> 
> * Here is a sample implementation and we can do that using `client-go` https://github.com/kubernetes/kubernetes/blob/c2e90cd1549dff87db7941544ce15f4c8ad0ba4c/pkg/kubectl/cmd/log.go#L141

+1 to this. We can use the sample implementation outlined in the link as a baseline for how to retrieve pod-container logs.
