### ISSUE TITLE
CLI extension failed when using diagnostic settings storage account

### ISSUE THREAD

**Issue by yangl900** [Azure/aks-periscope#11]
I'm using the AKS cluster diagnostic settings storage account. So I'm just running command

`az aks kollect`

I'm getting following error

Getting credentials for cluster <cluster-name>
Merged "<cluster-name>-admin" as current context in /tmp/tmpaMLFnX
Starts collecting diag info for cluster <cluster-name>
str() takes at most 1 argument (2 given)
Traceback (most recent call last):
  File "/home/anders/lib/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/anders/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
TypeError: str() takes at most 1 argument (2 given)

**Comment by JunSun17** [comment]
This looks to be some az cli related bug, like:
https://github.com/Azure/azure-cli/issues/10606

Please try installing the latest az cli and check if it works.

**Comment by rameshthangaraj** [comment]
Please upgrade the latest az cli version

**Comment by Tatsinnit** [comment]
💡 **Reason**: This was due to `az cli known issue` as mentioned above, periscope has nothing much to fix for this. Please add if this stands correct and I can re-open it. Thanks heaps.
