### ISSUE TITLE
Dbeaver azure.workflow.issue



### ISSUE THREAD

**Issue by hunksd6** [Azure/aks-periscope#126]

**Comment by Tatsinnit** [comment]
Thank you for opening this @hunksd6 , now sure the context but seems like either these issues get open by some bit or there are whole lot of details missing from last 5 issues which you have reported. 

For example: https://github.com/Azure/aks-periscope/issues/116 (references 3 more issues which have no details) 

I will close this and #125 as well, unless more details are added. Please fee free to open with more details.

thanks 🙏
