### ISSUE TITLE
pod container logs does not give back complete container logs 

### ISSUE THREAD

**Issue by sophsoph321** [Azure/aks-periscope#130]
**Describe the bug**
As we discussed offline, the pod container logs are not giving back complete logs. We identified the following issues in the pod container logs collector class 
1. We get pod container logs for only one of the containers in a pod, but not for all of the containers.  
2. The logs restrict the output of the following sample CLI command **kubectl logs extension-manager-5546f597d5-hv2kp -n azure-arc -c manager** to 2000 bytes. 
3. Line 152 in the collector class code (https://github.com/Azure/aks-periscope/blob/master/pkg/collector/pods_containerlogs_collector.go#L152) should be returnData = returnData + string(buf[:numBytes]) and not returnData = string(buf[:numBytes]). 

**To Reproduce**
Steps to reproduce the behavior: (for example)
1. Onboard a kind cluster onto Azure arc 
2. Deploy periscope on to the cluster 
3. Go to the storage container where the periscope logs are stored and find the pod container log corresponding to extension-manager
4. In the CLI run **kubectl get pods -n azure-arc**
5. Find the pod corresponding to extension manager and execute **kubectl logs extension-manager-5546f597d5-hv2kp -n azure-arc -c manager**
6. Compare the output of the CLI to the containerLog section in the periscope log from the storage account. You'll see that the contents of the containerLog section in the periscope log is a subset of the CLI output in step 5. 

**Expected behavior**
The pod container logs should return almost exactly the same content as the CLI output after executing **kubectl logs extension-manager-5546f597d5-hv2kp -n azure-arc -c manager**. And we should be getting pod container logs for all of the containers inside a pod, not just one. 

**Additional information**
Please see the code snippet for a sample pod container log we get back from periscope. 
`{"name":"extension-manager-5546f597d5-hv2kp","ready":"2/2","status":"Running","restart":0,"age":206185000000000,"containerName":"manager","containerLog":"nager.controller.extensionconfig\tStarting workers\t{\"reconciler group\": \"clusterconfig.azure.com\", \"reconciler kind\": \"ExtensionConfig\", \"worker count\": 1}\n"}`

**Comment by Tatsinnit** [comment]
Thank you @sophsoph321 , had an offline chat and will assign it to you. Please feel free to add quick change whenever. 🙏
