### ISSUE TITLE
Collect PDB related information.

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/aks-periscope#134]
This is a feature request, since we collect various information as an upgrade it will be amazing to log the `PodDisruptionBudget` information as well.

PDB in itself is a huge topic, but a log which can give enough data for the end user who understand will help in further analysis. Collecting this information and making this available via this tool helps in CSS or anyone analysing rule out PDB related issues.

Extras PDB information: https://kubernetes.io/docs/tasks/run-application/configure-pdb/ 

cc: @SriHarsha001 - might like this from this tool, (This has no direct connection with the other diagnostic tool which is based on rules engine) but I thought it might be good to add this information as PDB logs.

Any thoughts? please feel free to share.

**Comment by SriHarsha001** [comment]
@Tatsinnit - This is awesome. Yes, it makes complete sense to get a dump of PDB information from the cluster to analyze.
