### ISSUE TITLE
AKS Periscope install error

### ISSUE THREAD

**Issue by cbellee** [Azure/aks-periscope#16]
Hi, I'm trying to install periscope on a single nodepool, single node AKS cluster v1.15.7, but am experiencing the following error:

'The CustomResourceDefinition "diagnostics.aks-periscope.azure.github.com" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1"'

I'm running the latest Az CLI preview version.

$ az version
This command is in preview. It may be changed/removed in a future release.
{
  "azure-cli": "2.2.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.2.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.35",
    "front-door": "1.0.1"
  }
}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

----------------------------------------------------------------------------------------------

$ az aks kollect -g k8s-demo-rg -n k8s-demo --storage-account stork8sdemo

This will deploy a daemon set to your cluster to collect logs and diagnostic information and save them to the storage account stork8sdemo as outlined in http://aka.ms/AKSPeriscope.

If you share access to that storage account to Azure support, you consent to the terms outlined in http://aka.ms/DiagConsent.

Do you confirm? (y/N): y

Getting credentials for cluster k8s-demo 
Merged "k8s-demo-admin" as current context in /tmp/tmpyhy685qt

Starts collecting diag info for cluster k8s-demo 

Cleaning up aks-periscope resources if existing
serviceaccount "aks-periscope-service-account" deleted
serviceaccount "default" deleted
configmap "containerlogs-config" deleted
configmap "kubeobjects-config" deleted
configmap "nodelogs-config" deleted
daemonset.extensions "aks-periscope" deleted
secret "azureblob-secret" deleted
secret "default-token-xfp7q" deleted
clusterrolebinding.rbac.authorization.k8s.io "aks-periscope-role-binding" deleted
clusterrolebinding.rbac.authorization.k8s.io "aks-periscope-role-binding-view" deleted
clusterrole.rbac.authorization.k8s.io "aks-periscope-role" deleted_

Deploying aks-periscope
b'namespace/aks-periscope unchanged\nserviceaccount/aks-periscope-service-account created\nclusterrole.rbac.authorization.k8s.io/aks-periscope-role created\nclusterrolebinding.rbac.authorization.k8s.io/aks-periscope-role-binding created\nclusterrolebinding.rbac.authorization.k8s.io/aks-periscope-role-binding-view created\ndaemonset.apps/aks-periscope created\nsecret/azureblob-secret created\nconfigmap/containerlogs-config created\nconfigmap/kubeobjects-config created\nconfigmap/nodelogs-config created\nThe CustomResourceDefinition "diagnostics.aks-periscope.azure.github.com" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc0096b3320), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)\n'

**Comment by Tatsinnit** [comment]
:bulb: Further addition: essentially I test with `1.16.*` as well, with any higher version beyond the `default: 1.14.8` gives the same error.  

/triage

**Comment by blackbird-47** [comment]
Facing the same issue. Recently upgraded AKS to v1.16.7 form v1.14.7. Getting same error,
`'The CustomResourceDefinition "diagnostics.aks-periscope.azure.github.com" is invalid: spec.versions: Invalid value:`
Wasn't facing this before.

**Comment by kevinwedwards** [comment]
We're experiencing the same.  And we also just upgraded our AKS to v1.16.7 (but I've never run periscope before today).

**Comment by Tatsinnit** [comment]
**Update:** 

* Please try again, and this issue is fixed now, for future reference we have added a fix in cli to always grab the latest off periscope repo.
* tested on version `1.15 and 1.16`

Thanks,

**Comment by blackbird-47** [comment]
> **Update:** @cbellee + kevin + blackbird
> 
> * bulb Please try again, and this issue is **fixed** now, for future reference we have added a fix in cli to always grab the latest off periscope repo.
> * Tested on version `1.15 and 1.16`
> 
> Thanks,

Yes, tested with latest yaml. Works well, thank you.
