### ISSUE TITLE
periscope-image cannot be pulled

### ISSUE THREAD

**Issue by schoeffm** [Azure/aks-periscope#160]
**Describe the bug**
Deploying periscope as described in [`docs/appendix.md`](https://github.com/Azure/aks-periscope/blob/master/docs/appendix.md) by directly applying [`aks-periscope.yaml`](https://github.com/Azure/aks-periscope/blob/master/deployment/aks-periscope.yaml) fails since the referenced image cannot be pulled. The referenced registry `aksrepos.azurecr.io` doesn't resolve.

**To Reproduce**
Just follow the steps documented in here: [`docs/appendix.md`](https://github.com/Azure/aks-periscope/blob/master/docs/appendix.md)

**Expected behavior**
Images can be fetched - daemon-set is up and running.

**Comment by Tatsinnit** [comment]
💡 Thanks you so much reaching out @schoeffm, The file existing deployment will be deleted I think itss mentioned at the top of the file: https://github.com/Azure/aks-periscope/blob/855c9c955c11e52e852ae50a8fe1634f260fda73/deployment/aks-periscope.yaml#L1  

**Solution:**

* The latest image tag reside here: https://github.com/Azure/aks-periscope/releases/tag/v0.8
   * Image Tag: `mcr.microsoft.com/aks/periscope:0.0.8` 
* Sample YAML file:  
   * https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/deploymentyaml/aks-periscope.yaml#L1 

In the mean time  we have open #162 for removing this confusion, thank you so much for reporting this. 🙏☕️

**Comment by schoeffm** [comment]
Thanks for the infos ... I'll go ahead and try the referenced YAMLs.

**Comment by Tatsinnit** [comment]
Thank you 🙏, Glad it helped you, I will close this issue, please feel free to loop back if there is anything else.
