### ISSUE TITLE
az aks kollect fails to install periscope DaemonSet

### ISSUE THREAD

**Issue by schoeffm** [Azure/aks-periscope#161]
**Describe the bug**
Try to install/use periscope using the described az extension:
```az aks kollect -n aks-stefank8s-test -g rg-stefank8s-test --storage-account "staksdiagnostics3232"```

Installation of daemon-set failed (see screenshot)

**To Reproduce**
1. provision a suitable storage-account
2. execute the mentioned command ```az aks kollect -n aks-stefank8s-test -g rg-stefank8s-test --storage-account "staksdiagnostics3232"```

**Expected behavior**
DaemonSet gets installed and is up-and-running

**Screenshots**
<img width="1785" alt="Bildschirmfoto_2022-04-04_um_19_21_55" src="https://user-images.githubusercontent.com/2795468/161599094-413751cf-bc87-43a2-9fba-881e69c432c0.png">

**Desktop (please complete the following information):**
- Mac OS 
- az version
  ```
  {
    "azure-cli": "2.34.1",
    "azure-cli-core": "2.34.1",
    "azure-cli-telemetry": "1.0.6",
    "extensions": {
      "aks-preview": "0.5.58",
      "databricks": "0.8.0",
      "interactive": "0.4.5",
      "rdbms-connect": "1.0.1",
      "resource-graph": "2.1.0",
      "virtual-wan": "0.2.11"
    }
  }
```

**Comment by Tatsinnit** [comment]
☕️💡 Thank you so much @schoeffm for reporting this, it is an `az-cli` issue, but we have fixed it there as well and here is the tracking PR for the fix: https://github.com/Azure/azure-cli-extensions/pull/4630

**Comment by Tatsinnit** [comment]
💡 Thank for reporting this, The PR against the `cli-extension` is approved, hence closing this issue, the cli issue will be gone, once the PR is merged and released. Thanks.
