### ISSUE TITLE
Provide ability to delete aks-periscope

### ISSUE THREAD

**Issue by Sviatik** [Azure/aks-periscope#18]
Hello,

I can't find the right way to delete aks-periscope at all.
I guess it will be useful.

Thank you.

**Comment by Slivicon** [comment]
I don't know if it is the correct way, but I had to do:
`az extension remove --name aks-preview`
and also use `kubectl delete` commands for the relevant services\pods, if I remember right.

**Comment by Tatsinnit** [comment]
💡 To uninstall the instructions are mentioned here: https://github.com/Azure/aks-periscope#user-guide 

* To uninstall aks-periscope do `az extension remove --name aks-preview` 

Hope this is what you are looking for, closing this as no further action is in need, Thanks
