### ISSUE TITLE
Dependabot needs attention

### ISSUE THREAD

**Issue by peterbom** [Azure/aks-periscope#234]
We have Dependabot enabled, but it seems to have paused itself because we didn't pay it enough attention.

I think merging one of its PRs should revive it, so creating this to track that task.

I'd also like to look at the "Dependabot version updates" option, because I'm unsure if this is something we should have turned on.

**Comment by Tatsinnit** [comment]
Thank you for this awesomeness ❤️🙏☕️ I wonder 💭 if there is anything else under this tracking item or shall we close this, good news is seems like dependent bots are kicking along courtesy the PRs from you, @peterbom - just a ping as fyi - and whatever decision you make.

**Comment by peterbom** [comment]
Yes, I think this can be closed now. I see the pinned GH Actions dependencies are also getting updated, which is what prompted us to create this work item.
