### ISSUE TITLE
openvpn outbound test

### ISSUE THREAD

**Issue by tdihp** [Azure/aks-periscope#28]
as titled. currently periscope checks port 9000 for aks-link

**Comment by Tatsinnit** [comment]
💡 note currently there is a hard network bound dependency rule for ‘*:9000’ ports as documented here, : https://docs.microsoft.com/bs-latn-ba/azure/aks/limit-egress-traffic?view=azure-java-stable#required-outbound-network-rules-and-fqdns-for-aks-clusters

**Comment by tdihp** [comment]
Hmm, I'm merely suggesting to add a test also for the 1194 port which will be good to have and more tricky to implement.
For openvpn enabled clusters, the 9000 is open however should have no service listen to that.

**Comment by Tatsinnit** [comment]
Hiya @tdihp , Thank you for this, so essentially, so you think this fix done as part of another issue opened, will suffice the ask : https://github.com/Azure/aks-periscope/issues/84 . 

* https://github.com/Azure/aks-periscope/pull/91 

Thanks heaps

**Comment by tdihp** [comment]
Hi @Tatsinnit thanks for the update. I understand the change PR is based on the assumption that we will convert to konnectivity soon. Good enough for me if this is the way forward.

**Comment by Tatsinnit** [comment]
Thank you @tdihp for comment, sounds good, will close this for now and if there is anything else in future we can open it again.  🙏
