### ISSUE TITLE
OpenSUSE.org

### ISSUE THREAD

**Issue by hunksd6** [Azure/aks-periscope#34]

**Comment by Tatsinnit** [comment]
HIya @hunksd6, thank you so much for open this issue, could you please re-visit and add missed-details for this issue? kind regards.

**Comment by Tatsinnit** [comment]
Hiya  @hunksd6, thank you for the this but since this is open with no further details,  I will close this issue for now as there is no actionable item we can investigate, but happy for you/anyone to reopen in case there are more details relevant to this issue. kind regards,
