### ISSUE TITLE
Pods showing Evicted/OOM Killed state

### ISSUE THREAD

**Issue by NAIRAMAL** [Azure/aks-periscope#39]
My most of the pods are showing evicted or OOM killed state and getting restarted. Please help (Attached the snapshot for the reference)
![image](https://user-images.githubusercontent.com/45656452/113259577-e9f3be80-92ea-11eb-8b33-136f6ebf8b98.png)

**Comment by Tatsinnit** [comment]
Hiya and Thanks @NAIRAMAL , can you please share how this is related to the `aks-persicope` tool? I will await for loop back, thanks you once again.

**Comment by Tatsinnit** [comment]
Hiya @NAIRAMAL , thank you for the this but since this is open with no further details, I will close this issue for now as there is no actionable item we can investigate, but happy for you/anyone to reopen in case there are more details relevant to this issue. kind regards,
