### ISSUE TITLE
Override hardcoded /var/lib/kubelet/kubeconfig location in call to RunCommandOnHost

### ISSUE THREAD

**Issue by SanyaKochhar** [Azure/aks-periscope#43]
Context: evaluating using AKS-Periscope for [Open Service Mesh](https://github.com/openservicemesh/osm) on non-aks distros

When deploying aks-periscope on a [kind](https://kind.sigs.k8s.io/) cluster as described in the appendix.md, the following error is seen:
`Collector: networkoutbound, export data failed: Can't open kubeconfig file: Fail to run command on host: exit status 1`

This seems to be coming from https://github.com/Azure/aks-periscope/blob/da7f592b621163d6096e4a8fea7e95b80a145633/pkg/utils/helper.go#L56
when called by https://github.com/Azure/aks-periscope/blob/da7f592b621163d6096e4a8fea7e95b80a145633/pkg/utils/helper.go#L26

On exec'ing into the container (and replicating on an AKS cluster), it seems that the difference is that kind clusters do not have this kubeconfig at this `/var/lib/kubelet/kubeconfig` location. 

It would be useful if a flag could be added to be able to pass in this file path or pass in the api server fqdn to make it possible to use on non-aks distros

**Comment by Tatsinnit** [comment]
Hiya and Thank you for logging this, I will add appropriate label. Yes indeed, we noticed and planning to do some work items inline for this repo. We will soon add this as well in a road map **or** engage back. thank you.

**Comment by draychev** [comment]
@Tatsinnit Do you have an estimate on when or if this will be completed? It would be great to patch this and open up Periscope for broader use cases.

**Comment by Tatsinnit** [comment]
Thanks @draychev, cool, yeah this is not currently in the v1 road map, as currently this tool focused on `AKS` only scenario, I think in one of the internal email as well we discussed this. 

Moving forward no-doubt it will be good but I was willing to better stock take and decide that if we want to support broader `Non-AKS` scenario by-design.

**Comment by Tatsinnit** [comment]
Hiya @draychev and @SanyaKochhar - A look back for possible solution for this (will update once it is done), we have found much elegant solution for this and reason this `kubeconfig` was hardcoded was because it was using APIServer name was used as `containerName` so if we can easily supply that from the consuming tools which can access that information much easier. 

further details reside here: 

* https://github.com/Azure/aks-periscope/issues/99 
* https://github.com/Azure/aks-periscope/issues/92

Thanks heaps 🙏

**Comment by SanyaKochhar** [comment]
@Tatsinnit thanks for looping back on this. Took a look at the issues and the open PR and it seems like this is headed in the right direction

**Comment by Tatsinnit** [comment]
🙏 Thanks all for discussion, this is fixed as part of this recent release. https://github.com/Azure/aks-periscope/releases/tag/v0.5 , closing this issue.
