### ISSUE TITLE
feat: add SMI collector in Periscope

### ISSUE THREAD

**Issue by johnsonshi** [Azure/aks-periscope#67]
**Feature request**
Enhance periscope so that it collects SMI information from a cluster.

**Additional context**
This is blocked pending #48 being merged.
Once #48 is merged, I will open a PR that adds SMI collection capability to Periscope. This work has already been implemented in https://github.com/SanyaKochhar/aks-periscope/pull/30

**Comment by Tatsinnit** [comment]
💡🙏 thank you for creating this, FYI regarding #48 : it’s been few days it has merge conflict along with final changes we recommended, if we can fix that we can prioritise the changes and merge. Rest looks good. Thank you.
