### ISSUE TITLE
Add new collector for logs with container-d runtime

### ISSUE THREAD

**Issue by shwetamurali** [Azure/aks-periscope#68]
Azure Stack has switched its container runtime from docker to container-d. aks-periscope needs to be able to support container-d container log collection.

Error: `Collector: containerlogs, collect data failed: Fail to run command on host: exit status 127`

We need to add a new collector to work with container-d instead of just with docker.

**Comment by davidkydd** [comment]
KIND clusters have the same issue - logs in that case are in /var/log/pods and /var/logs/containers on the host. @shwetamurali have you started working on this?

**Comment by Tatsinnit** [comment]
🙏 Thanks all for this, had a discussion with @JiaxingSong , around this and closing this issue for now. Thanks.
