### ISSUE TITLE
Storage Account blob container name parametrization

### ISSUE THREAD

**Issue by alphaWizard** [Azure/aks-periscope#72]
Hi,

Right now, the storage blob container name is derived from the aks cluster's api server address/fqdn. So, in a way, it depends on the pattern for API server address of aks clusters. 

Is there a possibility to parametrize it, defaulting it to what it does right now, and add a parameter in yaml file to take the blob storage container name?

This will help extending the possibility to troubleshoot any Azure Arc Connected Kubernetes Cluster.

**Comment by alphaWizard** [comment]
Adding @sophsoph321 for visibility.

**Comment by Tatsinnit** [comment]
💡 Thank you for this. Linking this issue with - more detailed issue here: https://github.com/Azure/aks-periscope/issues/92 , Thanks heaps!

**Comment by Tatsinnit** [comment]
🙏 Thanks all for discussion, this is fixed as part of this recent release. https://github.com/Azure/aks-periscope/releases/tag/v0.5 , closing this issue.
