### ISSUE TITLE
invalid control character in URL

### ISSUE THREAD

**Issue by przemas75** [Azure/aks-periscope#9]
hello,
I have create SAS token in Azure portal, copied to zsh shell in macos and transformed with command:
`echo "SAS_TOKEN_STRING_COPIED"|base64`
Then, copy the output to yaml.
The pod logs then, look like this:
```
2019/09/24 06:04:21 Action: kubeobjects, process data, iteration: 0
2019/09/24 06:04:21 Action: kubeobjects, export data, iteration: 0
2019/09/24 06:04:21 Action: kubeobjects, export data failed at iteration: 0: Fail to build blob container url: parse https://somename
.blob.core.windows.net/othername-c64z61f2-hcp-westeurope-azmk8s-io?sv=2018-03-28&ss=b&srt=sco&sp=rwdlac&se=2020-09-24T13:46:49Z&st=2019-09-24T05:46:49Z&spr=https&sig=PARG0V00QEes01lwzE88Qrdn3x5Mb32RmMCtA4ZHqZQ=
: net/url: invalid control character in URL
```
(token is not real, obviously).

**Comment by mikepasco** [comment]
I was having the same issue as well, and found that echo output's a trailing newline that affects how encoding to base64 works. echo -n will disable the trailing newline output so try this:
`echo -n "SAS_TOKEN_STRING_COPIED"|base64`

**Comment by JunSun17** [comment]
@mikepasco Thanks for providing the tip to resolve this! I think this issue can be closed now,
